### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by TimeFlex1** [Ryzee119/XboxHDMI-Ryzee119#1]
Is this a dead project. Any updates?

**Comment by Ryzee119** [comment]
Hello!
* The project is definitely not dead, although I have certainly been getting distracted with other projects
* I have been waiting for something to be released. Very soon.
* My long term plan is to clean up what I have and open source it all here (even in its current state, which is ~99% working)

**Comment by TimeFlex1** [comment]
Hell yeah, I've been waiting for months for an update. I've been holding out from buying a Wii2Hdmi so I could do digital to digital, but I'm going to break down and go ahead and get a Wii2Hdmi and wait for your mod to come out. 

Keep up the great work, looking forward to it.

**Comment by TimeFlex1** [comment]
Also, I forgot to ask. Are you working on all video encoders (Conexant, Focus, and Xcalibur)?

**Comment by Ryzee119** [comment]
Yes it should work on all encoders/revs

**Comment by adamwtow** [comment]
Is this the same project? https://makemhz.com/products/xboxhdmi

**Comment by adamwtow** [comment]
Ah found the answer (that they're different projects) in the MakeMHz Discord chat. Interesting timing.

**Comment by Ryzee119** [comment]
Not my project but i have been aware of it for a long time.
They had a prototype before mine 😊 
As it turns out it is very similar to mine.

**Comment by GoTeamScotch** [comment]
Looking forward to this. Thanks for all your hard work, Ryzee!
