### ISSUE TITLE
Capacitor at C5A5

### ISSUE THREAD

**Issue by xboxnutter** [Ryzee119/XboxHDMI-Ryzee119#3]
Hi, was just going over this project and noticed in the install picture you have added an additional ceramic capacitor to the xbox motherboard at C5A5 which is marked for an electrolytic but unpopulated in factory state.

Do we need to add this ceramic cap? Any benefit and if so, what's its value?

Thanks.

**Comment by Ryzee119** [comment]
Likely just me testing stuff. I dont believe it is required.

**Comment by xboxnutter** [comment]
Oh righto' thanks for the reply and all your mods.

**Comment by Ryzee119** [comment]
Actually this xbox may have had a electrolytic there which was interfering with the flex. I may have just replaced it with a ceramic of the same value. If your xbox doesnt have anything there, all good 👍

**Comment by xboxnutter** [comment]
Yep, it's unpopulated there from factory, nothing in the way, it's a v1.1 which looks the same as yours in the picture, so guess you were adding testing items then. No worries.
